version: '3.4'
services:
  muchik.market.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9500:80"
  muchik.market.security.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9205:80"
  muchik.market.invoice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9201:80"
  muchik.market.pay.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9202:80"
  muchik.market.transaction.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9203:80"

